-- Initial Flyway schema for the current JPA entity model.
-- Designed to be compatible with PostgreSQL in production and H2 in tests.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    token VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_users_phone UNIQUE (phone),
    CONSTRAINT uq_users_token UNIQUE (token)
);

CREATE TABLE menu_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    price DOUBLE PRECISION NOT NULL,
    category VARCHAR(255),
    available BOOLEAN NOT NULL,
    recommended BOOLEAN,
    description VARCHAR(255),
    image_url VARCHAR(255),
    tag VARCHAR(255),
    is_veg BOOLEAN
);

CREATE INDEX idx_menu_item_category ON menu_item (category);
CREATE INDEX idx_menu_item_avail_rec ON menu_item (available, recommended);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(255),
    status VARCHAR(255),
    payment_status VARCHAR(255),
    razorpay_order_id VARCHAR(255),
    created_at TIMESTAMP
);

CREATE INDEX idx_orders_status ON orders (status);
CREATE INDEX idx_orders_razorpay_order_id ON orders (razorpay_order_id);

CREATE TABLE wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    balance BIGINT NOT NULL,
    CONSTRAINT uq_wallets_user_id UNIQUE (user_id),
    CONSTRAINT fk_wallets_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE wallet_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL,
    amount BIGINT NOT NULL,
    type VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    reference_id VARCHAR(128),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_wallet_transactions_wallet FOREIGN KEY (wallet_id) REFERENCES wallets (id)
);

CREATE INDEX idx_wallet_transactions_reference_id ON wallet_transactions (reference_id);
CREATE INDEX idx_wallet_transactions_wallet_created_at ON wallet_transactions (wallet_id, created_at);

CREATE TABLE order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_item_item FOREIGN KEY (item_id) REFERENCES menu_item (id)
);

CREATE INDEX idx_order_item_order_id ON order_item (order_id);
CREATE INDEX idx_order_item_item_id ON order_item (item_id);

