ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS last_status_changed_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS started_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS ready_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS priority VARCHAR(32),
    ADD COLUMN IF NOT EXISTS admin_note VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS assigned_admin VARCHAR(255);

UPDATE orders
SET last_status_changed_at = COALESCE(last_status_changed_at, created_at),
    priority = COALESCE(priority, 'NORMAL')
WHERE last_status_changed_at IS NULL
   OR priority IS NULL;

CREATE TABLE IF NOT EXISTS order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    previous_status VARCHAR(255),
    new_status VARCHAR(255) NOT NULL,
    changed_by VARCHAR(255),
    note VARCHAR(1000),
    changed_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_order_status_history_order FOREIGN KEY (order_id) REFERENCES orders (id)
);

CREATE INDEX IF NOT EXISTS idx_orders_priority ON orders (priority);
CREATE INDEX IF NOT EXISTS idx_orders_last_status_changed_at ON orders (last_status_changed_at);
CREATE INDEX IF NOT EXISTS idx_order_status_history_order_changed_at ON order_status_history (order_id, changed_at DESC);

