name: Deploy Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: "./frontend/dist"
          production-branch: main
          netlify-auth-token: nfp_2Wia9WRSAej8CQkbWtjCpw8KaJbTN6Hxa0ed
          netlify-site-id: 841a08f9-b26c-4573-9a79-4076f325431b